//
// Created by Aleksander Domagała on 08.11.2016.
//

#ifndef ENGINEERING_WORK_PROPERTY_TYPES_H
#define ENGINEERING_WORK_PROPERTY_TYPES_H

enum PROPERTY_TYPES {
    CAM_DEVICE_LIST,
    APP_VERSION
};

#endif //ENGINEERING_WORK_PROPERTY_TYPES_H
