//
// Created by Aleksander Domagała on 08.11.2016.
//

#ifndef ENGINEERINGWORK_PROPERTYTYPES_H
#define ENGINEERINGWORK_PROPERTYTYPES_H

enum PROPERTY_TYPES {
    CAM_DEVICE_LIST
};

#endif //ENGINEERINGWORK_PROPERTYTYPES_H
