//
// Created by Aleksander Domagała on 11/12/2016.
//

#ifndef ENGINEERING_WORK_APP_VERSION_INIT_H
#define ENGINEERING_WORK_APP_VERSION_INIT_H

#include "../cmake_auto_create/AutoGeneratedVariables.h"
#include "../propertie/AppVersion.h"
#include "../propertie/AppProperties.h"
#include "../propertie/PropertyTypes.h"

class AppVersionInit {
    const static int projectVersionMajor;
    const static int projectVersionMinor;
    const static int projectVersionPatch;

    AppVersionInit() = delete;

    AppVersionInit(const AppVersionInit &) = delete;

public:
    static void init();

    static void addAppVersionToAppProperties();
};


#endif //ENGINEERING_WORK_APP_VERSION_INIT_H
