#include "initialize/AppInit.h"
#include <iostream>
#include "cmake_auto_create/AutoGeneratedVariables.h"


int main() {

    int a = PROJECT_VERSION_PATCH;


    AppInit &init = AppInit::getInstance();

    init.initialization();

    AppProperties &property = AppProperties::getInstance();

    std::shared_ptr<const AppVersion> l = std::static_pointer_cast<const AppVersion>(
            property.getPropertyByName(PROPERTY_TYPES::APP_VERSION));


//    const std::vector<CamDevice>  ll = l->getDevicesList();

    int ab = l->getProjectVersionMajor();

    std::cout << "TES";

    return 0;
}
